version: "3"
services:
  mongo:
    image: "mongo:4"

  student_service:
    build: .
    image: "student-inventory-api/student_service:latest"
    environment:
      MONGO_URI: "mongodb://mongo:27017"
    depends_on:
      - mongo
    ports:
      - "8080:8080"
